// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cm_cdm_h)
#define octave_mx_cm_cdm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CDiagMatrix.h"
  extern OCTAVE_API ComplexMatrix operator + (const ComplexMatrix&, const ComplexDiagMatrix&);
  extern OCTAVE_API ComplexMatrix operator - (const ComplexMatrix&, const ComplexDiagMatrix&);
  extern OCTAVE_API ComplexMatrix operator * (const ComplexMatrix&, const ComplexDiagMatrix&);
#endif
