// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cdm_cm_h)
#define octave_mx_cdm_cm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CDiagMatrix.h"
  extern OCTAVE_API ComplexMatrix operator + (const ComplexDiagMatrix&, const ComplexMatrix&);
  extern OCTAVE_API ComplexMatrix operator - (const ComplexDiagMatrix&, const ComplexMatrix&);
  extern OCTAVE_API ComplexMatrix operator * (const ComplexDiagMatrix&, const ComplexMatrix&);
#endif
