// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cdm_s_h)
#define octave_mx_cdm_s_h 1
#include "octave-config.h"
#include "CDiagMatrix.h"
  extern OCTAVE_API ComplexDiagMatrix operator * (const ComplexDiagMatrix&, const double&);
  extern OCTAVE_API ComplexDiagMatrix operator / (const ComplexDiagMatrix&, const double&);
#endif
