// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_cnda_nda_h)
#define octave_mx_cnda_nda_h 1
#include "octave-config.h"
#include "CNDArray.h"
#include "dNDArray.h"
  extern OCTAVE_API ComplexNDArray operator + (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API ComplexNDArray operator - (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API ComplexNDArray product (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API ComplexNDArray quotient (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const ComplexNDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const ComplexNDArray&, const NDArray&);
#endif
