// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_dm_cdm_h)
#define octave_mx_dm_cdm_h 1
#include "octave-config.h"
#include "CDiagMatrix.h"
#include "dDiagMatrix.h"
  extern OCTAVE_API ComplexDiagMatrix operator + (const DiagMatrix&, const ComplexDiagMatrix&);
  extern OCTAVE_API ComplexDiagMatrix operator - (const DiagMatrix&, const ComplexDiagMatrix&);
  extern OCTAVE_API ComplexDiagMatrix product (const DiagMatrix&, const ComplexDiagMatrix&);
#endif
