// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fdm_fcm_h)
#define octave_mx_fdm_fcm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "fDiagMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatDiagMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatDiagMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatDiagMatrix&, const FloatComplexMatrix&);
#endif
