// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcdm_fdm_h)
#define octave_mx_fcdm_fdm_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "fDiagMatrix.h"
  extern OCTAVE_API FloatComplexDiagMatrix operator + (const FloatComplexDiagMatrix&, const FloatDiagMatrix&);
  extern OCTAVE_API FloatComplexDiagMatrix operator - (const FloatComplexDiagMatrix&, const FloatDiagMatrix&);
  extern OCTAVE_API FloatComplexDiagMatrix product (const FloatComplexDiagMatrix&, const FloatDiagMatrix&);
#endif
