// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcm_fdm_h)
#define octave_mx_fcm_fdm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "fDiagMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatComplexMatrix&, const FloatDiagMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatComplexMatrix&, const FloatDiagMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatComplexMatrix&, const FloatDiagMatrix&);
#endif
