// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcm_pm_h)
#define octave_mx_fcm_pm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "PermMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatComplexMatrix&, const PermMatrix&);
#endif
