// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fdm_fcs_h)
#define octave_mx_fdm_fcs_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "fDiagMatrix.h"
#include "oct-cmplx.h"
  extern OCTAVE_API FloatComplexDiagMatrix operator * (const FloatDiagMatrix&, const FloatComplex&);
  extern OCTAVE_API FloatComplexDiagMatrix operator / (const FloatDiagMatrix&, const FloatComplex&);
#endif
