// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcm_fs_h)
#define octave_mx_fcm_fs_h 1
#include "octave-config.h"
#include "fCMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API FloatComplexMatrix operator / (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_lt (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_le (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_ge (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_gt (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_eq (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_ne (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_and (const FloatComplexMatrix&, const float&);
  extern OCTAVE_API boolMatrix mx_el_or (const FloatComplexMatrix&, const float&);
#endif
