// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcs_fm_h)
#define octave_mx_fcs_fm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "oct-cmplx.h"
#include "fMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator / (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_lt (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_le (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_ge (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_gt (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_eq (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_ne (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_and (const FloatComplex&, const FloatMatrix&);
  extern OCTAVE_API boolMatrix mx_el_or (const FloatComplex&, const FloatMatrix&);
#endif
