// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fs_ui32nda_h)
#define octave_mx_fs_ui32nda_h 1
#include "octave-config.h"
#include "uint32NDArray.h"
  extern OCTAVE_API uint32NDArray operator + (const float&, const uint32NDArray&);
  extern OCTAVE_API uint32NDArray operator - (const float&, const uint32NDArray&);
  extern OCTAVE_API uint32NDArray operator * (const float&, const uint32NDArray&);
  extern OCTAVE_API uint32NDArray operator / (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const float&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const float&, const uint32NDArray&);
#endif
