// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fm_fcdm_h)
#define octave_mx_fm_fcdm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "fMatrix.h"
#include "fCDiagMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatMatrix&, const FloatComplexDiagMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatMatrix&, const FloatComplexDiagMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatMatrix&, const FloatComplexDiagMatrix&);
#endif
