// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fs_fcdm_h)
#define octave_mx_fs_fcdm_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
  extern OCTAVE_API FloatComplexDiagMatrix operator * (const float&, const FloatComplexDiagMatrix&);
#endif
