// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcs_fdm_h)
#define octave_mx_fcs_fdm_h 1
#include "octave-config.h"
#include "fCDiagMatrix.h"
#include "oct-cmplx.h"
#include "fDiagMatrix.h"
  extern OCTAVE_API FloatComplexDiagMatrix operator * (const FloatComplex&, const FloatDiagMatrix&);
#endif
