// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fcm_fcdm_h)
#define octave_mx_fcm_fcdm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "fCDiagMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatComplexMatrix&, const FloatComplexDiagMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatComplexMatrix&, const FloatComplexDiagMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator * (const FloatComplexMatrix&, const FloatComplexDiagMatrix&);
#endif
