// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fm_fcm_h)
#define octave_mx_fm_fcm_h 1
#include "octave-config.h"
#include "fCMatrix.h"
#include "fMatrix.h"
  extern OCTAVE_API FloatComplexMatrix operator + (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API FloatComplexMatrix operator - (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API FloatComplexMatrix product (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API FloatComplexMatrix quotient (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_lt (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_le (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_ge (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_gt (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_eq (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_ne (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_and (const FloatMatrix&, const FloatComplexMatrix&);
  extern OCTAVE_API boolMatrix mx_el_or (const FloatMatrix&, const FloatComplexMatrix&);
#endif
