// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_fs_fcnda_h)
#define octave_mx_fs_fcnda_h 1
#include "octave-config.h"
#include "fCNDArray.h"
  extern OCTAVE_API FloatComplexNDArray operator + (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API FloatComplexNDArray operator - (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API FloatComplexNDArray operator * (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API FloatComplexNDArray operator / (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const float&, const FloatComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const float&, const FloatComplexNDArray&);
#endif
