// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i8_fnda_h)
#define octave_mx_i8_fnda_h 1
#include "octave-config.h"
#include "int8NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
  extern OCTAVE_API int8NDArray operator + (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API int8NDArray operator - (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API int8NDArray operator * (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API int8NDArray operator / (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const octave_int8&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const octave_int8&, const FloatNDArray&);
#endif
