// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i8nda_nda_h)
#define octave_mx_i8nda_nda_h 1
#include "octave-config.h"
#include "int8NDArray.h"
#include "dNDArray.h"
  extern OCTAVE_API int8NDArray operator + (const int8NDArray&, const NDArray&);
  extern OCTAVE_API int8NDArray operator - (const int8NDArray&, const NDArray&);
  extern OCTAVE_API int8NDArray product (const int8NDArray&, const NDArray&);
  extern OCTAVE_API int8NDArray quotient (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const int8NDArray&, const NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const int8NDArray&, const NDArray&);
#endif
