// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i16nda_ui8nda_h)
#define octave_mx_i16nda_ui8nda_h 1
#include "octave-config.h"
#include "int16NDArray.h"
#include "uint8NDArray.h"
  extern OCTAVE_API boolNDArray mx_el_lt (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const int16NDArray&, const uint8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const int16NDArray&, const uint8NDArray&);
#endif
