// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i32nda_i64_h)
#define octave_mx_i32nda_i64_h 1
#include "octave-config.h"
#include "int32NDArray.h"
#include "oct-inttypes.h"
  extern OCTAVE_API boolNDArray mx_el_lt (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_le (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_ge (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_gt (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_eq (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_ne (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_and (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_or (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const int32NDArray&, const octave_int64&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const int32NDArray&, const octave_int64&);
#endif
