// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i64nda_ui64_h)
#define octave_mx_i64nda_ui64_h 1
#include "octave-config.h"
#include "int64NDArray.h"
#include "oct-inttypes.h"
  extern OCTAVE_API boolNDArray mx_el_lt (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_le (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_ge (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_gt (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_eq (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_ne (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_and (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_or (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const int64NDArray&, const octave_uint64&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const int64NDArray&, const octave_uint64&);
#endif
