// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_i32nda_fs_h)
#define octave_mx_i32nda_fs_h 1
#include "octave-config.h"
#include "int32NDArray.h"
  extern OCTAVE_API int32NDArray operator + (const int32NDArray&, const float&);
  extern OCTAVE_API int32NDArray operator - (const int32NDArray&, const float&);
  extern OCTAVE_API int32NDArray operator * (const int32NDArray&, const float&);
  extern OCTAVE_API int32NDArray operator / (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_lt (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_le (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_ge (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_gt (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_eq (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_ne (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_and (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_or (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const int32NDArray&, const float&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const int32NDArray&, const float&);
#endif
