// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_m_pm_h)
#define octave_mx_m_pm_h 1
#include "octave-config.h"
#include "dMatrix.h"
#include "PermMatrix.h"
  extern OCTAVE_API Matrix operator * (const Matrix&, const PermMatrix&);
#endif
