// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_nda_cnda_h)
#define octave_mx_nda_cnda_h 1
#include "octave-config.h"
#include "CNDArray.h"
#include "dNDArray.h"
  extern OCTAVE_API ComplexNDArray operator + (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API ComplexNDArray operator - (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API ComplexNDArray product (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API ComplexNDArray quotient (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const NDArray&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const NDArray&, const ComplexNDArray&);
#endif
