// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_nda_ui32nda_h)
#define octave_mx_nda_ui32nda_h 1
#include "octave-config.h"
#include "uint32NDArray.h"
#include "dNDArray.h"
  extern OCTAVE_API uint32NDArray operator + (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API uint32NDArray operator - (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API uint32NDArray product (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API uint32NDArray quotient (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const NDArray&, const uint32NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const NDArray&, const uint32NDArray&);
#endif
