// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_pm_cm_h)
#define octave_mx_pm_cm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "PermMatrix.h"
  extern OCTAVE_API ComplexMatrix operator * (const PermMatrix&, const ComplexMatrix&);
#endif
