// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_s_cdm_h)
#define octave_mx_s_cdm_h 1
#include "octave-config.h"
#include "CDiagMatrix.h"
  extern OCTAVE_API ComplexDiagMatrix operator * (const double&, const ComplexDiagMatrix&);
#endif
