// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_s_cnda_h)
#define octave_mx_s_cnda_h 1
#include "octave-config.h"
#include "CNDArray.h"
  extern OCTAVE_API ComplexNDArray operator + (const double&, const ComplexNDArray&);
  extern OCTAVE_API ComplexNDArray operator - (const double&, const ComplexNDArray&);
  extern OCTAVE_API ComplexNDArray operator * (const double&, const ComplexNDArray&);
  extern OCTAVE_API ComplexNDArray operator / (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const double&, const ComplexNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const double&, const ComplexNDArray&);
#endif
