// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui16nda_i8nda_h)
#define octave_mx_ui16nda_i8nda_h 1
#include "octave-config.h"
#include "uint16NDArray.h"
#include "int8NDArray.h"
  extern OCTAVE_API boolNDArray mx_el_lt (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_and (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_not_or (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const uint16NDArray&, const int8NDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const uint16NDArray&, const int8NDArray&);
#endif
