// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_mx_ui16_fnda_h)
#define octave_mx_ui16_fnda_h 1
#include "octave-config.h"
#include "uint16NDArray.h"
#include "oct-inttypes.h"
#include "fNDArray.h"
  extern OCTAVE_API uint16NDArray operator + (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API uint16NDArray operator - (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API uint16NDArray operator * (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API uint16NDArray operator / (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_lt (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_le (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ge (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_gt (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_eq (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_ne (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_and_not (const octave_uint16&, const FloatNDArray&);
  extern OCTAVE_API boolNDArray mx_el_or_not (const octave_uint16&, const FloatNDArray&);
#endif
