// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_sm_cm_h)
#define octave_smx_sm_cm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "dSparse.h"
#include "mx-s-cm.h"
#include "mx-cm-s.h"
#include "mx-m-cm.h"
#include "mx-cm-m.h"
#include "mx-s-cnda.h"
#include "mx-cnda-s.h"
#include "Sparse-op-defs.h"
  extern OCTAVE_API ComplexMatrix operator + (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API ComplexMatrix operator - (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseComplexMatrix product (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseComplexMatrix quotient (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_lt (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_le (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ge (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_gt (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_eq (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ne (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_and (const SparseMatrix&, const ComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_or (const SparseMatrix&, const ComplexMatrix&);
#endif
