// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_s_scm_h)
#define octave_smx_s_scm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "Sparse-op-defs.h"
  extern OCTAVE_API ComplexMatrix operator + (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API ComplexMatrix operator - (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseComplexMatrix operator * (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseComplexMatrix operator / (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_lt (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_le (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ge (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_gt (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_eq (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ne (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_and (const double&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_or (const double&, const SparseComplexMatrix&);
#endif
