// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_cs_sm_h)
#define octave_smx_cs_sm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "oct-cmplx.h"
#include "dSparse.h"
#include "Sparse-op-defs.h"
  extern OCTAVE_API ComplexMatrix operator + (const Complex&, const SparseMatrix&);
  extern OCTAVE_API ComplexMatrix operator - (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseComplexMatrix operator * (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseComplexMatrix operator / (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_lt (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_le (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ge (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_gt (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_eq (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ne (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_and (const Complex&, const SparseMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_or (const Complex&, const SparseMatrix&);
#endif
