// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_smx_cm_scm_h)
#define octave_smx_cm_scm_h 1
#include "octave-config.h"
#include "CMatrix.h"
#include "CSparse.h"
#include "Sparse-op-defs.h"
  extern OCTAVE_API ComplexMatrix operator + (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API ComplexMatrix operator - (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseComplexMatrix product (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseComplexMatrix quotient (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_lt (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_le (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ge (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_gt (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_eq (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_ne (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_and (const ComplexMatrix&, const SparseComplexMatrix&);
  extern OCTAVE_API SparseBoolMatrix mx_el_or (const ComplexMatrix&, const SparseComplexMatrix&);
#endif
