// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_cv_cs_h)
#define octave_vx_cv_cs_h 1
#include "octave-config.h"
#include "CColVector.h"
#include "dColVector.h"
#include "oct-cmplx.h"
  extern OCTAVE_API ComplexColumnVector operator + (const ColumnVector&, const Complex&);
  extern OCTAVE_API ComplexColumnVector operator - (const ColumnVector&, const Complex&);
  extern OCTAVE_API ComplexColumnVector operator * (const ColumnVector&, const Complex&);
  extern OCTAVE_API ComplexColumnVector operator / (const ColumnVector&, const Complex&);
#endif
