// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_ccv_cv_h)
#define octave_vx_ccv_cv_h 1
#include "octave-config.h"
#include "CColVector.h"
#include "dColVector.h"
  extern OCTAVE_API ComplexColumnVector operator + (const ComplexColumnVector&, const ColumnVector&);
  extern OCTAVE_API ComplexColumnVector operator - (const ComplexColumnVector&, const ColumnVector&);
  extern OCTAVE_API ComplexColumnVector product (const ComplexColumnVector&, const ColumnVector&);
  extern OCTAVE_API ComplexColumnVector quotient (const ComplexColumnVector&, const ColumnVector&);
#endif
