// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_crv_rv_h)
#define octave_vx_crv_rv_h 1
#include "octave-config.h"
#include "CRowVector.h"
#include "dRowVector.h"
  extern OCTAVE_API ComplexRowVector operator + (const ComplexRowVector&, const RowVector&);
  extern OCTAVE_API ComplexRowVector operator - (const ComplexRowVector&, const RowVector&);
  extern OCTAVE_API ComplexRowVector product (const ComplexRowVector&, const RowVector&);
  extern OCTAVE_API ComplexRowVector quotient (const ComplexRowVector&, const RowVector&);
#endif
