// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_cs_rv_h)
#define octave_vx_cs_rv_h 1
#include "octave-config.h"
#include "CRowVector.h"
#include "oct-cmplx.h"
#include "dRowVector.h"
  extern OCTAVE_API ComplexRowVector operator + (const Complex&, const RowVector&);
  extern OCTAVE_API ComplexRowVector operator - (const Complex&, const RowVector&);
  extern OCTAVE_API ComplexRowVector operator * (const Complex&, const RowVector&);
  extern OCTAVE_API ComplexRowVector operator / (const Complex&, const RowVector&);
#endif
