// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_fcs_frv_h)
#define octave_vx_fcs_frv_h 1
#include "octave-config.h"
#include "fCRowVector.h"
#include "oct-cmplx.h"
#include "fRowVector.h"
  extern OCTAVE_API FloatComplexRowVector operator + (const FloatComplex&, const FloatRowVector&);
  extern OCTAVE_API FloatComplexRowVector operator - (const FloatComplex&, const FloatRowVector&);
  extern OCTAVE_API FloatComplexRowVector operator * (const FloatComplex&, const FloatRowVector&);
  extern OCTAVE_API FloatComplexRowVector operator / (const FloatComplex&, const FloatRowVector&);
#endif
