// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_fcv_fcs_h)
#define octave_vx_fcv_fcs_h 1
#include "octave-config.h"
#include "fCColVector.h"
#include "fColVector.h"
#include "oct-cmplx.h"
  extern OCTAVE_API FloatComplexColumnVector operator + (const FloatColumnVector&, const FloatComplex&);
  extern OCTAVE_API FloatComplexColumnVector operator - (const FloatColumnVector&, const FloatComplex&);
  extern OCTAVE_API FloatComplexColumnVector operator * (const FloatColumnVector&, const FloatComplex&);
  extern OCTAVE_API FloatComplexColumnVector operator / (const FloatColumnVector&, const FloatComplex&);
#endif
