// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_fcv_fccv_h)
#define octave_vx_fcv_fccv_h 1
#include "octave-config.h"
#include "fCColVector.h"
#include "fColVector.h"
  extern OCTAVE_API FloatComplexColumnVector operator + (const FloatColumnVector&, const FloatComplexColumnVector&);
  extern OCTAVE_API FloatComplexColumnVector operator - (const FloatColumnVector&, const FloatComplexColumnVector&);
  extern OCTAVE_API FloatComplexColumnVector product (const FloatColumnVector&, const FloatComplexColumnVector&);
  extern OCTAVE_API FloatComplexColumnVector quotient (const FloatColumnVector&, const FloatComplexColumnVector&);
#endif
