// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_frv_fcrv_h)
#define octave_vx_frv_fcrv_h 1
#include "octave-config.h"
#include "fCRowVector.h"
#include "fRowVector.h"
  extern OCTAVE_API FloatComplexRowVector operator + (const FloatRowVector&, const FloatComplexRowVector&);
  extern OCTAVE_API FloatComplexRowVector operator - (const FloatRowVector&, const FloatComplexRowVector&);
  extern OCTAVE_API FloatComplexRowVector product (const FloatRowVector&, const FloatComplexRowVector&);
  extern OCTAVE_API FloatComplexRowVector quotient (const FloatRowVector&, const FloatComplexRowVector&);
#endif
