// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_s_ccv_h)
#define octave_vx_s_ccv_h 1
#include "octave-config.h"
#include "CColVector.h"
  extern OCTAVE_API ComplexColumnVector operator + (const double&, const ComplexColumnVector&);
  extern OCTAVE_API ComplexColumnVector operator - (const double&, const ComplexColumnVector&);
  extern OCTAVE_API ComplexColumnVector operator * (const double&, const ComplexColumnVector&);
  extern OCTAVE_API ComplexColumnVector operator / (const double&, const ComplexColumnVector&);
#endif
