// DO NOT EDIT -- generated by mk-ops.awk
#if ! defined (octave_vx_s_crv_h)
#define octave_vx_s_crv_h 1
#include "octave-config.h"
#include "CRowVector.h"
  extern OCTAVE_API ComplexRowVector operator + (const double&, const ComplexRowVector&);
  extern OCTAVE_API ComplexRowVector operator - (const double&, const ComplexRowVector&);
  extern OCTAVE_API ComplexRowVector operator * (const double&, const ComplexRowVector&);
  extern OCTAVE_API ComplexRowVector operator / (const double&, const ComplexRowVector&);
#endif
